project:
  type: website
  output-dir: docs

website:
  title: "tkk"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/kmmsks/tkk
        aria-label: GitHub
      
format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true

editor: visual

