---
title: "Tutkijan kevätkoulu 2024"
---

## Tervetuloa

Tervetuloa [Psykiatripäivillä](https://www.psy.fi){target="_blank"} toista kertaa järjestettävään Tutkijan kevätkouluun

**Aika:** Psykiatripäivien yhteydessä keskiviikkona 13.3.2024 klo 10.00-18.00, iltatilaisuus klo 19

**Paikka:** Paasitorni, Helsinki

## Abstraktikutsu

Tutkijan kevätkouluun haetaan ehdotuksia suullisiksi esityksiksi ja postereiksi. Esitysten tavoitteena on kuulla ajankohtaisista tutkimusaiheista, mahdollistaa verkostoituminen ja erityisesti harjoitella oman tieteellisen työn esittelyä yleisölle sekä toisten esitysten kommentointia. Tervetulleita ovat myös varhaisessa vaiheessa olevien tutkimusten kuvaukset. Tavoitteena keskustelu kannustavassa ja opettavaisessa ilmapiirissä.

Tutkijakoulun illallisella palkitaan sekä paras suullinen esitys että paras posteriesitys!

[Lähetä 250 sanan abstrakti, jossa esittelet joko]{style="font-size:18pt;font-weight: bold;"}

-   tutkimukseksi tuloksia otsikoilla **johdanto, metodit, tulokset, johtopäätökset,** tai

-   Väitöskirja-/tutkimushankettasi otsikoilla **johdanto, tutkimuksen tavoitteet, metodit, miksi tämä on tärkeää?**

### JATKETTU SUBMISSIOAIKA: Lähetä abstraktisi 7.2.2024 loppuun mennessä

Osoitteessa: <https://forms.gle/ep9UpuJo5vGwjXPQ6>

## Ilmoittautuminen

Ilmoittautuminen kevään Psykiatripäivien ilmoittautumisen yhteydessä.

Kulukorvauksista tieto on yhidstyksen nettisivuilla

## Ohjelma

+-------------+------------------------------------------------------------------------------------------------------+
| **Aika**    | **Ohjelma**                                                                                          |
+-------------+------------------------------------------------------------------------------------------------------+
| 10.00-12.30 | Posterit ja suulliset esitykset. Kahvi klo 11.                                                       |
+-------------+------------------------------------------------------------------------------------------------------+
| 12.30-13.30 | Lounas                                                                                               |
+-------------+------------------------------------------------------------------------------------------------------+
| 13.30-14.45 | Kuinka ottaa tilastotiede hallintaan?                                                                |
|             |                                                                                                      |
|             | Professori **Jouko Miettunen**, Väestöterveyden tutkimusyksikkö, Oulun yliopisto                     |
+-------------+------------------------------------------------------------------------------------------------------+
| 14.45-15.00 | Hengähdystauko                                                                                       |
+-------------+------------------------------------------------------------------------------------------------------+
| 15.00-16.15 | How to write a great introduction and discussion for a scientific article?                           |
|             |                                                                                                      |
|             | Ph.D. **Carolyn Brimley Norris**, Language Services, University of Helsinki                          |
+-------------+------------------------------------------------------------------------------------------------------+
| 16.15-16.45 | Kahvi                                                                                                |
+-------------+------------------------------------------------------------------------------------------------------+
| 16.45-18.00 | Hyvä tieteellinen käytäntö – käytännössä: laatuprotokollan valitsemisesta analyysien dokumentointiin |
|             |                                                                                                      |
|             | **Sebastian Therman**, erikoistutkija, THL                                                           |
+-------------+------------------------------------------------------------------------------------------------------+
| 19.00       | Iltatilaisuus                                                                                        |
+-------------+------------------------------------------------------------------------------------------------------+

## Järjestelytoimikunta

PJ:t Kimmo Suokas ja Toni Ali-Sisto

Heikki Laurikainen

Kaisa Luoto

Noora Scheinin

Kaija Järventausta

Helena Leppänen

Saana Karttunen

Virve Kekkonen

Erfan Jahangiri

## Edelliset tapahtuamt

[Tutkijan kevätkoulu 2023](https://github.com/kmmsks/tkk23)
